// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Openhab.Clinet.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Intent
    {
        /// <summary>
        /// Initializes a new instance of the Intent class.
        /// </summary>
        public Intent()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Intent class.
        /// </summary>
        public Intent(string name = default(string), IDictionary<string, string> entities = default(IDictionary<string, string>))
        {
            Name = name;
            Entities = entities;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entities")]
        public IDictionary<string, string> Entities { get; set; }

    }
}
